apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monteiro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SEU_USUARIO/SEU_REPOSITORIO'
    targetRevision: HEAD
    path: docker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
